### ISSUE TITLE
Background of card is not sustained

### ISSUE THREAD

**Issue by williamtrevis99** [sibsabu/sibils-personal-site#9]
Steps to Reproduce:

Load the site, observe the colour of the side-by-side, hit the dark mode button twice, and observe the slight blue color has now turned in to white.

Before button clicked:
![Screenshot 2021-04-15 at 16 09 25](https://user-images.githubusercontent.com/52605866/114892860-0cb2c680-9e05-11eb-9e34-bc1280d59389.png)
After:
![Screenshot 2021-04-15 at 16 09 32](https://user-images.githubusercontent.com/52605866/114892851-0a506c80-9e05-11eb-80f6-fc76084ed8eb.png)

**Comment by sibsabu** [comment]
finished task
